/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as Uncompressed from "./Uncompressed";
export interface IBloomFilterCompressionArgs {
    UNCOMPRESSED?: Uncompressed.Uncompressed;
}
export class BloomFilterCompression {
    public UNCOMPRESSED?: Uncompressed.Uncompressed;
    constructor(args?: IBloomFilterCompressionArgs) {
        let _fieldsSet: number = 0;
        if (args != null) {
            if (args.UNCOMPRESSED != null) {
                _fieldsSet++;
                this.UNCOMPRESSED = args.UNCOMPRESSED;
            }
            if (_fieldsSet > 1) {
                throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.INVALID_DATA, "Cannot read a TUnion with more than one set value!");
            }
            else if (_fieldsSet < 1) {
                throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.INVALID_DATA, "Cannot read a TUnion with no set value!");
            }
        }
    }
    public static fromUNCOMPRESSED(UNCOMPRESSED: Uncompressed.Uncompressed): BloomFilterCompression {
        return new BloomFilterCompression({ UNCOMPRESSED });
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("BloomFilterCompression");
        if (this.UNCOMPRESSED != null) {
            output.writeFieldBegin("UNCOMPRESSED", thrift.Thrift.Type.STRUCT, 1);
            this.UNCOMPRESSED.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): BloomFilterCompression {
        let _fieldsSet: number = 0;
        let _returnValue: BloomFilterCompression | null = null;
        input.readStructBegin();
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        _fieldsSet++;
                        const value_1: Uncompressed.Uncompressed = Uncompressed.Uncompressed.read(input);
                        _returnValue = BloomFilterCompression.fromUNCOMPRESSED(value_1);
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_fieldsSet > 1) {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.INVALID_DATA, "Cannot read a TUnion with more than one set value!");
        }
        else if (_fieldsSet < 1) {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.INVALID_DATA, "Cannot read a TUnion with no set value!");
        }
        if (_returnValue !== null) {
            return _returnValue;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read data for TUnion");
        }
    }
}
