/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as XxHash from "./XxHash";
export interface IBloomFilterHashArgs {
    XXHASH?: XxHash.XxHash;
}
export class BloomFilterHash {
    public XXHASH?: XxHash.XxHash;
    constructor(args?: IBloomFilterHashArgs) {
        let _fieldsSet: number = 0;
        if (args != null) {
            if (args.XXHASH != null) {
                _fieldsSet++;
                this.XXHASH = args.XXHASH;
            }
            if (_fieldsSet > 1) {
                throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.INVALID_DATA, "Cannot read a TUnion with more than one set value!");
            }
            else if (_fieldsSet < 1) {
                throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.INVALID_DATA, "Cannot read a TUnion with no set value!");
            }
        }
    }
    public static fromXXHASH(XXHASH: XxHash.XxHash): BloomFilterHash {
        return new BloomFilterHash({ XXHASH });
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("BloomFilterHash");
        if (this.XXHASH != null) {
            output.writeFieldBegin("XXHASH", thrift.Thrift.Type.STRUCT, 1);
            this.XXHASH.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): BloomFilterHash {
        let _fieldsSet: number = 0;
        let _returnValue: BloomFilterHash | null = null;
        input.readStructBegin();
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        _fieldsSet++;
                        const value_1: XxHash.XxHash = XxHash.XxHash.read(input);
                        _returnValue = BloomFilterHash.fromXXHASH(value_1);
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_fieldsSet > 1) {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.INVALID_DATA, "Cannot read a TUnion with more than one set value!");
        }
        else if (_fieldsSet < 1) {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.INVALID_DATA, "Cannot read a TUnion with no set value!");
        }
        if (_returnValue !== null) {
            return _returnValue;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read data for TUnion");
        }
    }
}
