/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as AesGcmV1 from "./AesGcmV1";
import * as AesGcmCtrV1 from "./AesGcmCtrV1";
export interface IEncryptionAlgorithmArgs {
    AES_GCM_V1?: AesGcmV1.AesGcmV1;
    AES_GCM_CTR_V1?: AesGcmCtrV1.AesGcmCtrV1;
}
export class EncryptionAlgorithm {
    public AES_GCM_V1?: AesGcmV1.AesGcmV1;
    public AES_GCM_CTR_V1?: AesGcmCtrV1.AesGcmCtrV1;
    constructor(args?: IEncryptionAlgorithmArgs) {
        let _fieldsSet: number = 0;
        if (args != null) {
            if (args.AES_GCM_V1 != null) {
                _fieldsSet++;
                this.AES_GCM_V1 = args.AES_GCM_V1;
            }
            if (args.AES_GCM_CTR_V1 != null) {
                _fieldsSet++;
                this.AES_GCM_CTR_V1 = args.AES_GCM_CTR_V1;
            }
            if (_fieldsSet > 1) {
                throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.INVALID_DATA, "Cannot read a TUnion with more than one set value!");
            }
            else if (_fieldsSet < 1) {
                throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.INVALID_DATA, "Cannot read a TUnion with no set value!");
            }
        }
    }
    public static fromAES_GCM_V1(AES_GCM_V1: AesGcmV1.AesGcmV1): EncryptionAlgorithm {
        return new EncryptionAlgorithm({ AES_GCM_V1 });
    }
    public static fromAES_GCM_CTR_V1(AES_GCM_CTR_V1: AesGcmCtrV1.AesGcmCtrV1): EncryptionAlgorithm {
        return new EncryptionAlgorithm({ AES_GCM_CTR_V1 });
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("EncryptionAlgorithm");
        if (this.AES_GCM_V1 != null) {
            output.writeFieldBegin("AES_GCM_V1", thrift.Thrift.Type.STRUCT, 1);
            this.AES_GCM_V1.write(output);
            output.writeFieldEnd();
        }
        if (this.AES_GCM_CTR_V1 != null) {
            output.writeFieldBegin("AES_GCM_CTR_V1", thrift.Thrift.Type.STRUCT, 2);
            this.AES_GCM_CTR_V1.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): EncryptionAlgorithm {
        let _fieldsSet: number = 0;
        let _returnValue: EncryptionAlgorithm | null = null;
        input.readStructBegin();
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        _fieldsSet++;
                        const value_1: AesGcmV1.AesGcmV1 = AesGcmV1.AesGcmV1.read(input);
                        _returnValue = EncryptionAlgorithm.fromAES_GCM_V1(value_1);
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        _fieldsSet++;
                        const value_2: AesGcmCtrV1.AesGcmCtrV1 = AesGcmCtrV1.AesGcmCtrV1.read(input);
                        _returnValue = EncryptionAlgorithm.fromAES_GCM_CTR_V1(value_2);
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_fieldsSet > 1) {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.INVALID_DATA, "Cannot read a TUnion with more than one set value!");
        }
        else if (_fieldsSet < 1) {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.INVALID_DATA, "Cannot read a TUnion with no set value!");
        }
        if (_returnValue !== null) {
            return _returnValue;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read data for TUnion");
        }
    }
}
