/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as EncryptionAlgorithm from "./EncryptionAlgorithm";
export interface IFileCryptoMetaDataArgs {
    encryption_algorithm: EncryptionAlgorithm.EncryptionAlgorithm;
    key_metadata?: Buffer;
}
export class FileCryptoMetaData {
    public encryption_algorithm: EncryptionAlgorithm.EncryptionAlgorithm;
    public key_metadata?: Buffer;
    constructor(args: IFileCryptoMetaDataArgs) {
        if (args != null && args.encryption_algorithm != null) {
            this.encryption_algorithm = args.encryption_algorithm;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[encryption_algorithm] is unset!");
        }
        if (args != null && args.key_metadata != null) {
            this.key_metadata = args.key_metadata;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("FileCryptoMetaData");
        if (this.encryption_algorithm != null) {
            output.writeFieldBegin("encryption_algorithm", thrift.Thrift.Type.STRUCT, 1);
            this.encryption_algorithm.write(output);
            output.writeFieldEnd();
        }
        if (this.key_metadata != null) {
            output.writeFieldBegin("key_metadata", thrift.Thrift.Type.STRING, 2);
            output.writeBinary(this.key_metadata);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): FileCryptoMetaData {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_1: EncryptionAlgorithm.EncryptionAlgorithm = EncryptionAlgorithm.EncryptionAlgorithm.read(input);
                        _args.encryption_algorithm = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: Buffer = input.readBinary();
                        _args.key_metadata = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.encryption_algorithm !== undefined) {
            return new FileCryptoMetaData(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read FileCryptoMetaData from input");
        }
    }
}
